<?php

return array (
  'version' => '5.4.3',
  'title' => 'Services',
  'type' => 'services',
  'id' => '60526dda6873c',
  'updated' => 1616015056,
  'columns' => 
  array (
    '60526de3283128' => 
    array (
      'type' => 'column-featured_image',
      'label' => 'Image',
      'width' => '130',
      'width_unit' => 'px',
      'featured_image_display' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '120',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60526de3283128',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '250',
      'width_unit' => 'px',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '60526dfc2147b0' => 
    array (
      'type' => 'column-excerpt',
      'label' => 'Excerpt',
      'width' => '',
      'width_unit' => '%',
      'excerpt_length' => '20',
      'before' => '',
      'after' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60526dfc2147b0',
    ),
    '60526e04d6872c' => 
    array (
      'type' => 'column-content',
      'label' => 'Content',
      'width' => '',
      'width_unit' => '%',
      'string_limit' => 'word_limit',
      'excerpt_length' => '20',
      'before' => '',
      'after' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'editable_type' => 'textarea',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60526e04d6872c',
    ),
    '60526e0d4b8520' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Service Categories',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'service-categories',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'enable_term_creation' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60526e0d4b8520',
    ),
    '60526eade4dd30' => 
    array (
      'type' => 'column-status',
      'label' => 'Status',
      'width' => '100',
      'width_unit' => 'px',
      'use_icon' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60526eade4dd30',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'on',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);